{% set name = "threadloop" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/threadloop-{{ version }}.tar.gz
  sha256: 8b180aac31013de13c2ad5c834819771992d350267bddb854613ae77ef571944

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - tornado

test:
  imports:
    - threadloop
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/breerly/threadloop
  summary: Tornado IOLoop Backed Concurrent Futures
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - msarahan
